# Generated by Django 3.2.2 on 2021-06-06 18:55

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
                ('keywords', models.CharField(max_length=255, verbose_name='Ключевое слово')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('status', models.CharField(choices=[('True', 'Виден'), ('False', 'Не виден')], max_length=20, verbose_name='Статус видимости')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Короткая метка')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('keywords', models.CharField(max_length=255, verbose_name='Ключевое слово')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Цена')),
                ('amount', models.IntegerField(default=0, verbose_name='Кол-во')),
                ('variant', models.CharField(choices=[('none', 'Нет'), ('white', 'Белый'), ('black', 'Чёрный'), ('green', 'Зелённый')], default='None', max_length=10, verbose_name='Цвет')),
                ('country', models.CharField(choices=[('none', 'Нет'), ('turkey', 'Турция'), ('russia', 'Россия'), ('china', 'Китай')], default='None', max_length=10, verbose_name='Страна')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Детали')),
                ('slug', models.SlugField(unique=True, verbose_name='Метка')),
                ('status', models.CharField(choices=[('True', 'Виден'), ('False', 'Не виден')], max_length=10, verbose_name='Статус')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50, verbose_name='Субъект')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Отзыв')),
                ('rate', models.IntegerField(default=5, verbose_name='Оценка')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='IP')),
                ('status', models.CharField(choices=[('New', 'Новый'), ('True', 'Виден'), ('False', 'Не виден')], default='New', max_length=10, verbose_name='Статус')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
        ),
    ]
