# Generated by Django 3.2.2 on 2021-06-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210607_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('turkey', 'Турция'), ('russia', 'Россия'), ('china', 'Китай')], max_length=10, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('white', 'Белый'), ('black', 'Чёрный'), ('green', 'Зелённый')], max_length=10, verbose_name='Цвет'),
        ),
    ]
