# Generated by Django 3.2.2 on 2021-05-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210521_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('none', 'Нет'), ('turkey', 'Турция'), ('russia', 'Россия'), ('china', 'Китай')], default='None', max_length=10, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('none', 'Нет'), ('white', 'Белый'), ('black', 'Чёрный'), ('green', 'Зелённый')], default='None', max_length=10, verbose_name='Цвет'),
        ),
    ]
