# Generated by Django 3.2.2 on 2021-06-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, null=True, verbose_name='Цена'),
        ),
    ]
