# Generated by Django 3.2.2 on 2021-06-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='variant',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.AddField(
            model_name='product',
            name='max_height',
            field=models.IntegerField(null=True, verbose_name='Максимальная ширина'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_width',
            field=models.IntegerField(null=True, verbose_name='Максимальная ширина'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_height',
            field=models.IntegerField(null=True, verbose_name='Минимальная высота'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_width',
            field=models.IntegerField(null=True, verbose_name='Минимальная ширина'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_rome_cloth',
            field=models.IntegerField(default=0, null=True, verbose_name='Цена ткани для римскиой шторы'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_rome_cornice',
            field=models.IntegerField(default=0, null=True, verbose_name='Цена римского карниза'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена товара'),
        ),
    ]
