# Generated by Django 3.2.2 on 2021-05-25 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0005_auto_20210521_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50, verbose_name='Субъект')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Отзыв')),
                ('rate', models.IntegerField(default=5, verbose_name='Оценка')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='IP')),
                ('status', models.CharField(choices=[('New', 'Новый'), ('True', 'Виден'), ('False', 'Не виден')], default='New', max_length=10, verbose_name='Статус')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID Пользователя')),
            ],
        ),
    ]
