# Generated by Django 3.2.2 on 2021-06-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210610_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_height',
            field=models.IntegerField(default=0, verbose_name='Максимальная высота (см.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='max_width',
            field=models.IntegerField(default=0, verbose_name='Максимальная ширина (см.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='min_height',
            field=models.IntegerField(default=0, verbose_name='Минимальная высота (см.)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='min_width',
            field=models.IntegerField(default=0, verbose_name='Минимальная ширина (см.)'),
            preserve_default=False,
        ),
    ]
