# Generated by Django 3.2.2 on 2021-05-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_user_id_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
