# Generated by Django 3.2.2 on 2021-06-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Рейтинг товара'),
        ),
    ]
