# Generated by Django 3.2.2 on 2021-06-09 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210607_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinformation',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
    ]
