# Generated by Django 3.2.2 on 2021-06-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_companyinformation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
