# Generated by Django 3.2.2 on 2021-06-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_contactmessage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(max_length=255, verbose_name='Ваше сообщение'),
        ),
    ]
