# Generated by Django 3.2.2 on 2021-06-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_shopcart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ip',
        ),
    ]
