# Generated by Django 3.2.2 on 2021-06-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Accepted', 'Принят'), ('Preaparing', 'Собирается'), ('OnShipping', 'Передан в доставку'), ('Completed', 'Доставлен'), ('Canceled', 'Отменён')], default='Новый', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('New', 'Новый'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled')], default='New', max_length=10),
        ),
    ]
