# Generated by Django 3.2.2 on 2021-06-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210601_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Принят', 'Принят'), ('Собирается', 'Собирается'), ('Передан в доставку', 'Передан в доставку'), ('Доставлен', 'Доставлен'), ('Отменён', 'Отменён')], default='Новый', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Принят', 'Принят'), ('Отменён', 'Отменён')], default='Новый', max_length=20),
        ),
    ]
