# Generated by Django 3.2.2 on 2021-06-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210609_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopcart',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
