# Generated by Django 3.2.2 on 2021-06-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210610_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.IntegerField(),
        ),
    ]
