# Generated by Django 3.2.2 on 2021-06-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('Картой онлайн', 'Онлайн'), ('Картой при получении', 'Картой'), ('Наличными при получении', 'Наличными')], default='Онлайн', max_length=50),
        ),
    ]
